#! /bin/sh
#xset -dpms &
#xset s off &
#setxkbmap pl &
#wal -R &
#xrandr --output DP-0 --mode 1920x1080 --rate 144.00 &
#picom --experimental-backend &
flameshot &
zsh /home/kubaws/.config/polybar/launch.sh &
. "${HOME}/.cache/wal/colors.sh"
bspc config normal_border_color "$color1"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color7"
bspc config presel_feedback_color "$color7"
bspc config urgent_border_color "$color1"



pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-0 -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap          11

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

